name: Minetopia-Core
version: 1.0-SNAPSHOT
main: nl.minetitan.Core
api-version: 1.13
commands:
  mod:
    description: 'Alle moderation tools van MineTopia'
  banking:
    description: 'Admin commando voor bankieren'
  time:
    description: 'Zie je online tijd'
  prefix:
    description: 'Wijzig jouw prefix!'
  chatkleur:
    description: 'Wijzig jouw chatkleur!'
  pin:
    description: 'Start een pinbetaling met dit commando.'
  plot:
    description: 'Plot commando'
  plotinfo:
    description: 'Plotinfo commando'